Update routes due ti release 4.0.ts
Avaiga/website pull request #62
Opened 2024-10-15 07:12 UTC by RymMichaut

editing top bar menu leading to the documentation due to the release 4.0 launch

2024-10-15 07:29 UTC, FlorianJacta approved these changes
LGTM

2024-10-15 12:39 UTC, jrobinAV requested changes

2024-10-15 12:49 UTC, FabienLelaquais requested changes

2024-10-15 13:50 UTC, jrobinAV approved these changes

2024-10-23 07:13 UTC, FabienLelaquais approved these changes
👌

2024-10-23 07:13 UTC, merged